import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      style={{ colorScheme: "only light" }}
    >
      <body className="min-h-full flex flex-col bg-[#f2efea] text-[#141414]">
        {children}
      </body>
    </html>
  );
}
